;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; │░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░│
;; └────────────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

;; Use pywal.sh in scripts directory to use colors from an image/wallpaper.

;; main colors
; background = #1E1F29
; background = #191A22
background = #1c1c1c 
background-alt = #282a36
foreground = #f8f8f2
foreground-alt = #282a36
primary = #282a36

white = #FFFFFF
black = #000000
red = #EC7875
pink = #EC6798
purple = #BE78D1
blue = #75A4CD
cyan = #00C7DF
teal = #00B19F
green = #61C766
lime = #B9C244
yellow = #EBD369
amber = #EDB83F
orange = #E57C46
brown = #AC8476
gray = #9E9E9E
indigo = #6C77BB
blue-gray = #6D8895

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

dracula = #1E1F29
dracula-select = #6B5297
;dracula-select = #50fa7b
dracula-background = #1E1F29
