#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI
#bspc monitor -d I II III VI

# bspc config automatic_scheme alternate

bspc config border_width		0
bspc config window_gap		    5

bspc config split_ratio          0.5
bspc config center_pseudo_tiled   true
bspc config borderless_monocle   true
bspc config gapless_monocle      false
# bspc config normal_border_color "#FFFFFF"
bspc config normal_border_color "#191622"
bspc config focused_border_color  "#0f1011"
#bspc config focused_border_color  "#6B5297"


bspc rule -a "VirtualBox Manager" desktop='^3' follow=on
bspc rule -a "VirtualBox" desktop='^3' follow=on state=floating
bspc rule -a "Virt-manager" desktop='^3' follow=on
bspc rule -a "mpv" desktop='^3' follow=on state=floating center=true rectangle=1200x625+100+100
bspc rule -a "wps" desktop='^3' follow=on
bspc rule -a "libreoffice-startcenter" desktop='^4' follow=on
bspc rule -a "Pcmanfm" desktop='^3'	follow=on state=floating center=true rectangle=1200x625+100+100
bspc rule -a "tutanota-desktop" desktop='^4' follow=on state=floating center=true rectangle=1200x625+100+100
bspc rule -a "Nemo" desktop='^3' follow=on
bspc rule -a "Brave-browser" desktop='^2' follow=on focus=on
bspc rule -a "zen" desktop='^2' follow=on focus=on
bspc rule -a "LibreWolf" desktop='^2' follow=on focus=on
bspc rule -a "Cromite" desktop='^2' follow=on focus=on
bspc rule -a "Alacritty" desktop='^1' follow=on state=floating center=true rectangle=1200x625+100+100
bspc rule -a "mplayer2" state=floating
bspc rule -a "Viewnior" state=floating
bspc rule -a "burp-StartBurp" state=floating center=true rectangle=1200x625+100+100
bspc rule -a "SVPManager" desktop='^4'state=floating
bspc rule -a "Kupfer.py" focus=on
bspc rule -a "Screenkey" manage=off

xsetroot -cursor_name left_ptr &
feh --bg-fill ~/Pictures/Walpaper/dracula
/usr/bin/bash ~/.config/polybar/launch.sh --blocks 
export _JAVA_AWT_WM_NONREPARENTING=1; wmname LG3D
